config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'terms#index'

  resources :terms, only: %i(index new create destroy show update)

  get 'pages/about' => 'pages#about'

  get 'api/v1/terms/description.json' => 'terms#description'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role
  include Mongoid::Document
  has_and_belongs_to_many :users
  belongs_to :resource, :polymorphic => true

  field :name, :type => String

  index({
    :name => 1,
    :resource_type => 1,
    :resource_id => 1
  },
  { :unique => true})

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/term.rb
class Term
  include Mongoid::Document
  field :title, type: String
  field :eng_title, type: String
  field :description, type: String
  field :uri, type: String

  def to_json
    {
      id: id.to_s,
      description: description,
      title: title,
      eng_title: eng_title,
      uri: uri
    }
  end

  # get rus text from rdfs:comment
  def upload_rus(sparql, keyword)
    sparql.query(
      <<-SPARQL
        SELECT DISTINCT ?concept ?description
        WHERE {
          ?concept rdfs:comment ?description .
          ?concept rdfs:label "#{keyword}"@en .
          FILTER ( lang(?description) = "ru" )
        }
      SPARQL
    )
  end

  # get rus text from dbo:abstract
  def upload_rus_mod(sparql, keyword)
    sparql.query(
      <<-SPARQL
        SELECT DISTINCT ?concept ?description
        WHERE {
          ?concept dbo:abstract ?description .
          ?concept rdfs:label "#{keyword}"@en .
          FILTER ( lang(?description) = "ru" )
        }
      SPARQL
    )
  end

  # get eng text from rdfs:comment
  def upload_eng(sparql, keyword)
    sparql.query(
      <<-SPARQL
        SELECT DISTINCT ?concept ?description
        WHERE {
          ?concept rdfs:comment ?description .
          ?concept rdfs:label "#{keyword}"@en .
          FILTER ( lang(?description) = "en" )
        }
      SPARQL
    )
  end

  # get eng text from dbo:abstract
  def upload_eng_mod(sparql, keyword)
    sparql.query(
      <<-SPARQL
        SELECT DISTINCT ?concept ?description
        WHERE {
          ?concept dbo:abstract ?description .
          ?concept rdfs:label "#{keyword}"@en .
          FILTER ( lang(?description) = "en" )
        }
      SPARQL
    )
  end

  def correct_keyword
    sparql = SPARQL::Client.new('http://dbpedia.org/sparql')
    result = sparql.query(
      <<-SPARQL
        SELECT DISTINCT  ?label
        WHERE
          { ?concept  rdfs:label    ?label ;
                      rdf:type      owl:Thing
            FILTER ( lang(?label) = "en" )
            FILTER (lcase(str(?label)) = "#{eng_title.downcase}")
          }
        LIMIT 1
      SPARQL
    )
    result.first[:label].value
  end

  def load_descriptions
    sparql = SPARQL::Client.new("http://dbpedia.org/sparql")
    keyword = correct_keyword
    solutions = []
    solutions << upload_rus(sparql, keyword).first[:description].value
    solutions << upload_rus_mod(sparql, keyword).first[:description].value
    solutions << upload_eng(sparql, keyword).first[:description].value
    solutions << upload_eng_mod(sparql, keyword).first[:description].value
    solutions
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to after_sign_in_path_for(current_user), alert: exception.message
  # end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :authenticate_user!, only: %i(new create update)

  def index
    @terms = Term.all
  end

  def new
  end

  def create
    @term = Term.create! term_params
    @descriptions = @term.load_descriptions
  rescue => e
    @error = e.message
  end

  def update
    @term = Term.find params[:id]
    @term.description = params[:term][:description]
    @term.save!
    redirect_to terms_path
  rescue => _e
  end

  def description
    raise 'missing argument \'term\'' if params[:term].blank?
    render json: {description: Term.where(eng_title: Regexp.new(params[:term], 'i')).first.description.to_s}, status: :ok
  rescue => e
    render json: {message: e.message}, status: :internal_server_error
  end

  private

  def term_params
    params.require(:term).permit(:title, :eng_title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title LOD Glossary | ipm.semantics
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      a.navbar-brand href="/"  LOD Glossary
      #navbar.collapse.navbar-collapse
        ul.nav.navbar-nav
          li
            a href="/pages/about" About
          - if current_user.blank?
            li
              a href="/users/sign_in"  Sign in
    .container
      == yield

app/views/pages/about.html.slim
.pages-header
  h1 About

.container
  p
    h3 Public API
    p If you want to get description about a term, please use public API:
    code GET /api/v1/terms/description?term=some_term_here
  
.container
  p
    h3 Contacts
    p 
      | If you have some comments or you want to contact us then you should use this email: 
      code
        a href='mailto:m.navrotskiy@gmail.com' m.navrotskiy@gmail.com

app/views/terms/create.html.slim
.page-header
  h1 Add description

- if @error.blank?
  = react_component 'TermDescription', {term: @term.to_json, descriptions: @descriptions, authenticity_token: form_authenticity_token}
- else
  .alert.alert-danger role='alert'= @error

app/views/terms/index.html.slim
.page-header
  h1 LOD Glossary

- unless current_user.blank?
  p
    a.btn.btn-success href="#{new_term_path}"
      = fa_icon 'fw plus', text: 'Add new term'

table.table.table-hover.table-striped
  thead
    tr
      th Term
      th Description
      th
  tbody
    - @terms.each do |term|
      tr
        td= "#{term.title} (#{term.eng_title})"
        td= term.description || '-'

app/views/terms/new.html.slim
.page-header
  h1 Add new term

.panel.panel-default
  .panel-body
    = form_tag '/terms', method: 'post'
      .form-group
        = label_tag :title, 'Title'
        = text_field :term, :title, class: 'form-control', placeholder: 'Input russian title', required: true
      .form-group
        = label_tag :eng_title, 'Eng title'
        = text_field :term, :eng_title, class: 'form-control', placeholder: 'Input english title', required: true
      .form-group
        a.btn.btn-default href='/' Cancel
        = submit_tag 'Next', class: 'btn btn-success'